name: computer_12
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  share: ^2.0.4
  rating_dialog: ^2.0.4
  lottie: ^3.1.0
  animated_splash_screen: ^1.3.0
  bulleted_list: ^0.0.1+0.1a
  url_launcher: ^6.3.0
  facebook_audience_network: ^1.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/unit_1/
    - images/unit_2/
    - images/unit_4/
    - images/unit_5/
    - images/unit_6/
    - images/unit_3/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
